### ISSUE TITLE
Error validates :name,    :presence => {:if => Proc.new{SpreeContactUs.require_name}}

### ISSUE THREAD

**Issue by sechix** [2beDigital/solidus_contact_us#1]
I have installed correctly the gem and the page but I get this error:

uninitialized constant Spree::ContactUs::Contact::SpreeContactUs
23 validates :name,    :presence => {:if => Proc.new{SpreeContactUs.require_name}}

**Comment by SergiCarrasco** [comment]
Hi @sechix,
We are still in the process of implementing Solidus, so we still have this gem for Solidus in "beta".
Anyway, we could not reproduce the bug you mentioned, but we have had some similar ones related to the eager_load in Rails 5.
This [link](http://collectiveidea.com/blog/archives/2016/07/22/solutions-to-potential-upgrade-problems-in-rails-5) talks about it.
Could it be that the error is due to this?
